### PR TITLE
Update and rename inf2d.md to inf2d-RA.md

### PR DESCRIPTION
**Pull request by Riotshielder21**
update name, amendment to grade allocation for course

### CODE REVIEW

**Comment by qaisjp** [comment]
Why rename? The official course acronym is inf2d: https://course.inf.ed.ac.uk/

**Comment by qaisjp** [comment]
(Renaming will break automation as course.inf.ed.ac.uk is scraped into this repo daily!)

**Comment by Riotshielder21** [comment]
Ah, I have learned so much already.  How much of the pages are automated

**Comment by qaisjp** [comment]
This data: https://github.com/compsoc-edinburgh/betterinformatics/blob/master/_data/courses.yml

**Comment by Riotshielder21** [comment]
Thanks, I'll check it out.

**Pull request merged**
