### PR TITLE
Replace former lecture storage link

### PR DESCRIPTION
**Pull request by dylan-thinnes**
Replaces an old, broken link to lectures up to 2016 which has now been taken down with SlightlyBetterLectures.
Lectures are still hosted outside the uni's servers on SBL, if that's a problem please reject.

### CODE REVIEW

**Comment by dylan-thinnes** [comment]
I'm making this a pull request so you can reject it if necessary.

**Comment by rphi** [comment]
Does inf1 not use Echo360? I'd say if it does it would be worth linking to that as well (especially as that player allows you to change playback speed, and is the official service) - saying that having the videos outside of that is very worthwhile - Echo360 is a tad naff

**Comment by qaisjp** [comment]
since it contains inf1 content only, perhaps it could be linked here instead? https://github.com/compsoc-edinburgh/betterinformatics/blob/master/_sections/inf1/general.md

**Comment by rphi** [comment]
Although we could start moving other content into SlightlyBetterLectures? Lob those JS things into a Chrome extension or something and then just have someone from each year who clicks the button every few days.

**Comment by rphi** [comment]
Additionally, could we potentially move this into either a DICE server (if they would let us) or onto TARDIS (if they have the disk space)? Keeps it within the ed.ac.uk domain and saves you the S3 fees.

**Comment by qaisjp** [comment]
Lets move discussion about the actual lectures service to #41.

Also, perhaps we could include the link to the old lectures on your lectures site @dylan-thinnes? That way someone can still find the old lectures?

**Pull request merged**
