### PR TITLE
Adding my google drive folder

### PR DESCRIPTION
**Pull request by SimonRovder**
A collection of past paper solutions written by Emilia Bogdanova, Constance Crowe, Patrick Green, Margus Lind, Angus Pearson, James Renwick, Simon Rovder, Paul Sinclair and Jenny Wilson.

### CODE REVIEW

**Comment by neanias** [comment]
Seeing Constance always throws me off

**Comment by aptgetmoo** [comment]
Thank you so much! These look fantastic :)

**Comment by qaisjp** [comment]
Would it be possible to eventually move these files to [the centralised Drive](https://betterinformatics.com/drive)? (so it's all in one place / any possible mistakes can be fixed later)

(the owner has to do it)

**Comment by SimonRovder** [comment]
I wasn't aware of that one, sure, I can add it there.

**Pull request merged**
